### ISSUE TITLE
Dataset Clarification

### ISSUE THREAD

**Issue by arminzirak** [eth-sri/TFix#16]
Hello all,
I hope you are feeling well!
My name is Armin, and I am a master's student at University of Calgary. I started using your great tool (TFix) for my thesis. I want to thank you for the great GitHub repo you provided that is very easy to use, well-formatted, and well established which makes my study much easier. 

As part of my study, I encountered a couple of questions. Can you have a look at them? any comment will be very helpful for me.
I am confused between data files. There are four files as below:
1. data_autofix_tracking_eslint_filtered.json
2. data_autofix_tracking_eslint_final.json
3. data_autofix_tracking_repo_specific_filtered.json
4. data_autofix_tracking_repo_specific_final.sjon

 Can you please give a hint about the difference between "_filtered.json" files and "_final.json" data files? I believe you used "_final.json" data for training and testing as "clean test" Is that correct? If so, what is the usage of "_filtered.json" files? Are they used as the "random test" dataset?

Also, is there any difference between "Eslint" files and "repo_specific" files? because they are concatenated to each other so I assumed that the difference is not important as long as I use both of them as the data source.

Finally, do you know why the "target file" fields in "_filtered.json" files include the whole file but in "_final.json" files only contain a patch around the buggy code? And by any chance, do you have access to the full files of target files as well? 

Thanks

**Comment by BBerabi** [comment]
Hi Armin, 

Sorry for the late reply! I am very happy that you found the repo well-structured and formatted. I invested some time into it. 😄 Also, I appreciate to hear that you are doing a thesis on program repair.

1. `Can you please give a hint about the difference between "_filtered.json" files and "_final.json" data files?
`

Your explanation is correct. `_final.json` files were used for training and testing as `clean_test`. So, here the word `final` means: after everything was applied (mining, data cleaning, etc). On the other hand, again as you pointed out, `_filtered.json` files correspond to `random_test`. Here, `filtered` means "`_removed_samples_in_data_cleaning`". 

Those samples were removed because the extracted target_code was likely not correct.

2. `Also, is there any difference between "Eslint" files and "repo_specific" files? `
We ran EsLint with two different configurations, providing different set of rules. We called one config eslint and the other repo_specific. That is why it is safe to merge them and yes you can use both as data source.

3. `Finally, do you know why the "target file" fields in "_filtered.json" files include the whole file but in "_final.json" files only contain a patch around the buggy code?`

Yes, you are right. For the good samples, (final) I added a larger patch into the `target_file` field for debugging purposes (to debug the target code extraction process). This was also mentioned in the README. For the filtered samples, that was not needed since they were noisy and cleaned. There was nothing to debug. That's why I just left the whole file for them.

4. And by any chance, do you have access to the full files of target files as well?
Yes, I know. You have all the required elements to fetch the original files. Github uses the following URL pattern:

https://github.com/<organization>/<repo_name>/commits/<commit_sha>
You have all the required fields in our data for each sample. I can guess that you probably want to fetch those files programtically. In this case, you need to use libgit2, which is an amazing library for git. https://libgit2.org/ 

It has suport for C++, Python and many more languages. You need to dig into the documentation a bit.


I hope this clarifies everything. I will try to be more responsive. 

Feel free to let me know if you have further questions.

Best,
Berkay

**Comment by BBerabi** [comment]
Hi again @arminzirak 

I would like to close this issue if everything is clarified. I will close it in few days if I do not hear anything from you.

Thanks!
Berkay

**Comment by smith-co** [comment]
@bberabi11 can you please point out how from these jsons can we use the exact same split for test and train that you used for TFix evaluation?

**Comment by BBerabi** [comment]
Hi @smith-co, 

I answered you in the issue you created.

Best,
Berkay
