### ISSUE TITLE
Testing on Java Codes

### ISSUE THREAD

**Issue by YunhaoZZ** [eth-sri/TFix#2]
Hello dear authors,

I am a student and really like your work. I was wondering if I could test the model provided on some other data like Defects4J. Just testing not training on my own data.

I checked the .json files in the data folder and the scripts about preparing data, but still I could not find out how to preprocess the data like Defects4J, for example. Could you please give me some advice on this?

Thank you!
Henry

**Comment by bberabi11** [comment]
Hi Henry,

Thank you for your interest and nice feedback! I am happy to help you! Let me first explain the top-level pipeline briefly and then I can give you specific recommendations for your task.

We have a function called [`GetDataAsPython()`](https://github.com/eth-sri/TFix/blob/main/data_reader.py#L63) in `data_reader.py` that takes as an argument a path to a JSON file, reads it, and converts the objects in JSON file to python objects called [`DataPoint`](https://github.com/eth-sri/TFix/blob/main/data_reader.py#L25).

This function is then called in [`transformers_globa.py`](https://github.com/eth-sri/TFix/blob/764c19b3ebd3ed6e20bbe9e6056979947e483dcd/hf_transformers/transformers_global.py#L68) to get a python list of `DataPoint` objects. However, our model requires text to be trained and tested so this list is passed to the `create_data` function in order to get the text representations. (See [this](https://github.com/eth-sri/TFix/blob/764c19b3ebd3ed6e20bbe9e6056979947e483dcd/hf_transformers/transformers_global.py#L74) and [this](https://github.com/eth-sri/TFix/blob/764c19b3ebd3ed6e20bbe9e6056979947e483dcd/hf_transformers/prepare_data.py#L43)) In file `prepare_data.py`, this is done by using the [`GetT5Representation()`](https://github.com/eth-sri/TFix/blob/main/data_reader.py#L52) function of the `DataPoint` class.

Now, regarding your task, I have two suggestions for you depending on what you want. I will explain both and then you can decide.

If you just want to play around with the model on this new dataset, a simple script like the one below would work. Please refer to [HuggingFace](https://huggingface.co/transformers/model_doc/t5.html#t5forconditionalgeneration) documentation for more details.

```
defects4j_samples = GetSamplesFromDefectfs4J() # this returns a list of strings
tfix_model = T5ForConditionalGeneration.from_pretrained("path to our model on your local directory")
tfix_tokenizer = T5Tokenizer.from_pretrained('path to our model on your local directory')
for sample in defects4j_samples:
  input_ids = tokenizer(sample, return_tensors="pt").input_ids
  output_ids = tfix_model.generate(input_ids).
  prediction = tfix_tokenizer.decode(output_ids)
  # do something with the prediction
```
Essentially, you need to read the new data and create a text representation of it. Defects4J already provides an isolated version of the buggy code according to their README.

If you want to use our code for more complex tasks, my suggestion is the following.

- Write your own reader function in `data_reader.py` (just like `GetDataPointAsPython`) and read the Defect4J samples and convert them to `DataPoint` and return a list of `DataPoint` just like `GetDataAsPython`. In your case, most of the fields of DataPoint will be empty due to having a different dataset but that's okay.

- Write your own `GetT5RepresentationForDefects4J` function for creating the input text for your data set and use this function in `prepare_data.py` (instead of the default one `GetT5Representation`) to get the representation that you desire.

- Note that out testing code is in `transformers_global.py` and starts at [here](https://github.com/eth-sri/TFix/blob/764c19b3ebd3ed6e20bbe9e6056979947e483dcd/hf_transformers/transformers_global.py#L136). For your case, the lines in the scope `    if args.eval_all:` are not relevant so you can start to look at testing code from [here](https://github.com/eth-sri/TFix/blob/764c19b3ebd3ed6e20bbe9e6056979947e483dcd/hf_transformers/transformers_global.py#L190) and take inspirations. :) 

I hope this helps and feel free to reach out to me in case you have further questions.

Best,
Berkay
