### ISSUE TITLE
Query about accuracy calculation

### ISSUE THREAD

**Issue by nashid** [eth-sri/TFix#20]
I see many code snippets where the error is not fixed at the reported `warning_line`. For example:

**Buggy JavaScript:**
```
} else if (relativeTop > decreaseIncreaseLimit) {
          qx.bom.AnimationFrame.request(function() {
            this._increaseSelectedIndex(target);## warning line
          }, this);
        }
```
  
**Fixed JavaScript:**
```
} else if (relativeTop > decreaseIncreaseLimit) {
          this._increaseSelectedIndex(target);
        }
```

Linter warnings:
```
"rule_id" : no-invalid-this
"evidence": Unexpected 'this'.
"warning_line": this._increaseSelectedIndex(target);
```

So the developer fix was to remove these tokens `qx.bom.AnimationFrame.request(function() {`. If I understand it correctly, if it is an `exact match`, TFix would remove the tokens `qx.bom.AnimationFrame.request(function() {` and the match would look eactly like the fixed javaScript i.e. `string equality` check.

Also do you want to share the `accuarcy` calculation scripts for error removal?

**Comment by nashid** [comment]
One more example here:

**Buggy JavaScript:**
```
this._logs = [];
```
   
**Fixed JavaScript:**
```
var _enableDebugTrace = false;
```

**Linter warnings:**

```
"rule_id" : no-invalid-this
"evidence": Unexpected 'this'.
"warning_line": this._logs = [];
```

Is it an exact match if model removes the `this._logs = [];` line? Or the model needs to also suggest `var _enableDebugTrace = false;` to count as an exact match.

I dont think model would learn to generate a new token sequence like `var _enableDebugTrace = false;` out of the blue.

So I guess if the model removes the line `this._logs = [];`, you count it as an exact match. Can you please clarify my queries?

**Comment by BBerabi** [comment]
Hi Nashid,

The model also needs to suggest `var _enableDebugTrace = false;` so that we can count it as an exact match. You are correct that it will not learn to generate it out of the blue, but it is just what it is. That is the reason why we argue in the paper that ExactMatch is a lower bound. Therefore, we introduced ErrorRemoval to handle cases where our model generated a correct fix, but the fix did not exactly match the one in the commit. however, ErorrRemoval is then an upper bound. It can happen that the model somehow removed the error, but it might not be a valid fix.

The accuracy calculation scripts were written in C++, and we can not share them quickly for several reasons related to confidentiality, licensing and dependencies. We would essentially leak some code from our code base. It is hard for me to get out only that particular part as our code base has various dependencies. But that process is not very hard to reproduce, the discussion at the end of this following issue can be helpful: https://github.com/eth-sri/TFix/issues/13

Best,
Berkay

**Comment by ghost** [comment]
I am closing this issue as it is answered and has been inactive for awhile. If you have other questions, please open a new issue. Thank you!
